### ISSUE TITLE
add_prim_lib should use indexed strings from DeviceResources instead of nested LogicalNetlist

### ISSUE THREAD

**Issue by gatecat** [SymbiFlow/python-fpga-interchange#47]
I found some subtle breakage in the current nexus data because the nexus `primLibs` netlist contains local string indices, stored within the netlist's `strList`, whereas the existing code assumes that `primLibs` shares a `strList` with the parent device resources.

It's unclear which of the two options is better here - if the current approach, as used by the xilinx database is preferred then the primitive library patching tool will need updating.

cc @litghost

**Comment by litghost** [comment]
> it might be missing for writing.

Ya, it is missing.  The reader takes an argument to a string indexer (see here: https://github.com/SymbiFlow/python-fpga-interchange/blob/b4331eff339790b9eaa095083aec5e628712bb75/fpga_interchange/interchange_capnp.py#L572)

The writer should take a string indexer, which is optional.  If the string indexer isn't provided, it builds an internal one.  Then the patch tool can provide a string indexer seeded from the DeviceResource's, and update the `strList` after patching in the prims library.
