### ISSUE TITLE
Why get_primitive_library is using self.strs

### ISSUE THREAD

**Issue by mtdudek** [SymbiFlow/python-fpga-interchange#95]
@gatecat 
I'm having issue with `get_primitive_library`, when it calls `to_logical_netlist` it passes self.strs, this causes cellDecls names to no longer reference strings inside primLibs.strList but strings inside self.strs.
This is unclear to me, why we are doing it this way. I assume this was done due to some devices not having strList set and their names were referring to global names.

**Comment by gatecat** [comment]
Have you seen the discussion behind this in #47 ?

**Comment by mtdudek** [comment]
May bad, did not see this issue.
